In [2]:
#!pip3 install torch torchvision torchaudio

# [Pytorch 기반 선형회귀]

- [1] 모듈 로딩 및 데이터 준비 <hr>

In [3]:
### ===> 모듈로딩
import torch                            # 파이토치 텐서 및 기본 함수들 관련 모듈
import torch.nn as nn                   # 인공신경망 층 관련 모듈
import torch.nn.functional as F         # 인공신경망 관련 함수들 모듈
import torch.optim as optim             # 인공신경망 최적화 관련 모듈

In [4]:
### ===> 랜덤 시드(random seed) 설정
torch.manual_seed(1)

In [5]:
### ===> 데이터 준비
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 이거 그냥 만들었기 때문에 requires_grad = False로 설정 유지)

In [6]:
print(f'x_train : {x_train.shape}, {x_train.ndim} \n{x_train}')
print(f'y_train : {y_train.shape}, {y_train.ndim} \n{y_train}')

x_train : torch.Size([3, 1]), 2 
tensor([[1.],
        [2.],
        [3.]])
y_train : torch.Size([3, 1]), 2 
tensor([[2.],
        [4.],
        [6.]])


- [2] 학습 위한 준비 <hr>

In [7]:
### ===> 가중치 및 절편 데이터 생성 및 초기화
# - 가중치 W            : 0으로 초기화하고 학습 통해 값이 변경되는 변수 명시함
# - requires_grad=True : 학습을 통해 계속 값이 변경되는 변수임 의미
# torch.zeros(텐서 원소 갯수)
W = torch.zeros(1, requires_grad=True)   # 피처가 1개니까 가중치 1개짜리 만들어놈
b = torch.zeros(1, requires_grad=True)   # bias는 어쩌파 1개니까 1개짜리 만들어놈

print(f'W : {W}, b : {b}')

W : tensor([0.], requires_grad=True), b : tensor([0.], requires_grad=True)


In [8]:
### ===> 경사하강법 설정 : W,b 업데이트
# W,b 변수, 학습률지정
optimizer = optim.SGD([W, b], lr=0.01)

# W, b를 업데이트하기 위해서 경사하강법을 적용함

In [9]:
W

tensor([0.], requires_grad=True)

In [10]:
b

tensor([0.], requires_grad=True)

In [11]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

- [3] 학습 진행 <hr>

In [12]:
### ===> 학습 진행
# - 에포크 : 처음부터~끝까지 학습하는 것 의미

nb_epochs = 100                 # 100번 학습   (처음부터 끝까지 100번 보겠다)

for epoch in range(nb_epochs + 1):

    # H(x) 계산 = XW+b => 예측값
    y_pre = x_train * W + b

    # cost 계산 = 합((예측값 - 정답)**2)
    cost = torch.mean((y_pre - y_train) ** 2)      # => Mean Square Error에 해당함

    # cost로 H(x) 개선
    optimizer.zero_grad()           # gradient 0으로 초기화   (0으로 초기화하지 않으면 누적이 되기떄문에 업데이트하면 누적된것에 됨!)
    
    cost.backward()                 # 비용 함수 미분하여 gradient 계산
    print(f'수식을 w로 미분한 값 : {W.grad}')

    optimizer.step()                # W, b 업데이트
    print(f'업데이트 된 W : {W.grad}, b : {b.grad}')


    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print(f'Epoch {epoch:4d}/{nb_epochs} W: { W.item():.3f}, b: {b.item():.3f} Cost: {cost.item():.6f}')
        
# 우리가 머신러닝에서 fit 했던 과정을 이런 유사한 과정으로 흘러간다.

수식을 w로 미분한 값 : tensor([-18.6667])
업데이트 된 W : tensor([-18.6667]), b : tensor([-8.])
Epoch    0/100 W: 0.187, b: 0.080 Cost: 18.666666
수식을 w로 미분한 값 : tensor([-16.6044])
업데이트 된 W : tensor([-16.6044]), b : tensor([-7.0933])
수식을 w로 미분한 값 : tensor([-14.7710])
업데이트 된 W : tensor([-14.7710]), b : tensor([-6.2873])
수식을 w로 미분한 값 : tensor([-13.1408])
업데이트 된 W : tensor([-13.1408]), b : tensor([-5.5707])
수식을 w로 미분한 값 : tensor([-11.6915])
업데이트 된 W : tensor([-11.6915]), b : tensor([-4.9337])
수식을 w로 미분한 값 : tensor([-10.4030])
업데이트 된 W : tensor([-10.4030]), b : tensor([-4.3673])
수식을 w로 미분한 값 : tensor([-9.2573])
업데이트 된 W : tensor([-9.2573]), b : tensor([-3.8639])
수식을 w로 미분한 값 : tensor([-8.2388])
업데이트 된 W : tensor([-8.2388]), b : tensor([-3.4163])
수식을 w로 미분한 값 : tensor([-7.3332])
업데이트 된 W : tensor([-7.3332]), b : tensor([-3.0184])
수식을 w로 미분한 값 : tensor([-6.5280])
업데이트 된 W : tensor([-6.5280]), b : tensor([-2.6647])
수식을 w로 미분한 값 : tensor([-5.8121])
업데이트 된 W : tensor([-5.8121]), b : tensor([-2.3503])
수식을 w로 

- [4] 학습 후 모델 파라미터 확인 <hr>

In [116]:
### ===> 학습 완료 후의 W, b  텐서 값 확인
W.item(), b.item()

(1.7456912994384766, 0.5780722498893738)

- [5] 예측 <hr>

In [117]:
### ===> x값 넣고 y값 확인
pre_y = W*3+b
pre_y.item()

# 여기에 나온게 우리가 머신러닝에서 predict 했던 메서드가 이런 과정으로 흘러갔던 것이다.

5.815145969390869

In [118]:
## optimizer.zero_grad()가 필요한 이유
## 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시키는 특징

w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

  z = 2*w

  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0
