# 방향
- 이중분류 할것이다: 사진이 주어졌을때 이게 개냐 ~ 아니냐 ~

# 할거
- 3개의 함수 : 학습, 검증 및 테스트, 예측
- 모델 : 층, 층별 노드, 퍼셉트론 수 조절한게 있어야 함

In [ ]:
from PIL import Image
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_openml 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import torch
import torch.nn.functional as F 
import torch.nn as nn 
from torch.utils.data import Dataset, DataLoader, random_split
import torch.optim as optim 
import torchmetrics.functional as metrics

In [ ]:
# 회색으로 변환 후 이미지 파일 불러오기
# img = Image.open('C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_000002.jpg').convert('L')
# pix = np.array(img)
# print(img.size)
# x = np.array(img)
# print(x)
# print(x.shape)

(512, 512)
[[165 163 161 ... 104 104 104]
 [165 163 161 ... 104 104 104]
 [165 163 161 ... 104 104 104]
 ...
 [158 157 157 ...  91  90  90]
 [156 155 155 ...  92  92  92]
 [155 154 155 ...  93  93  93]]
(512, 512)


In [ ]:
no_file_num = []
for i in range(2, 10):
    try:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_00000{i}.jpg').convert('L')
        pix = np.array(img)
        x = np.array(img)
        print(f"{i}번 이미지 shape => {x.shape}")
    except:
        print(f'예외 발생! => {i}번 이미지 없음')
        no_file_num.append(i)

2번 이미지 shape => (512, 512)
3번 이미지 shape => (512, 512)
4번 이미지 shape => (512, 512)
5번 이미지 shape => (512, 512)
6번 이미지 shape => (512, 512)
예외 발생! => 7번 이미지 없음
8번 이미지 shape => (512, 512)
9번 이미지 shape => (512, 512)


In [ ]:
for i in range(10, 100):
    try:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_0000{i}.jpg').convert('L')
        pix = np.array(img)
        x = np.array(img)
        print(f"{i}번 이미지 shape => {x.shape}")
    except:
        print(f'예외 발생! => {i}번 이미지 없음')
        no_file_num.append(i)

예외 발생! => 10번 이미지 없음
11번 이미지 shape => (512, 512)
12번 이미지 shape => (512, 512)
13번 이미지 shape => (512, 512)
14번 이미지 shape => (512, 512)
15번 이미지 shape => (512, 512)
16번 이미지 shape => (512, 512)
17번 이미지 shape => (512, 512)
18번 이미지 shape => (512, 512)
19번 이미지 shape => (512, 512)
20번 이미지 shape => (512, 512)
21번 이미지 shape => (512, 512)
22번 이미지 shape => (512, 512)
23번 이미지 shape => (512, 512)
24번 이미지 shape => (512, 512)
25번 이미지 shape => (512, 512)
26번 이미지 shape => (512, 512)
27번 이미지 shape => (512, 512)
28번 이미지 shape => (512, 512)
29번 이미지 shape => (512, 512)
30번 이미지 shape => (512, 512)
31번 이미지 shape => (512, 512)
32번 이미지 shape => (512, 512)
33번 이미지 shape => (512, 512)
34번 이미지 shape => (512, 512)
35번 이미지 shape => (512, 512)
36번 이미지 shape => (512, 512)
예외 발생! => 37번 이미지 없음
38번 이미지 shape => (512, 512)
39번 이미지 shape => (512, 512)
예외 발생! => 40번 이미지 없음
41번 이미지 shape => (512, 512)
42번 이미지 shape => (512, 512)
43번 이미지 shape => (512, 512)
44번 이미지 shape => (512, 512)
45번 이미지 shape => (512, 512)
46번 이미지 shape

In [ ]:
for i in range(100, 1010):
    try:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_000{i}.jpg').convert('L')
        pix = np.array(img)
        x = np.array(img)
        print(f"{i}번 이미지 shape => {x.shape}")
    except:
        print(f'예외 발생! => {i}번 이미지 없음')
        no_file_num.append(i)

100번 이미지 shape => (512, 512)
101번 이미지 shape => (512, 512)
102번 이미지 shape => (512, 512)
103번 이미지 shape => (512, 512)
104번 이미지 shape => (512, 512)
105번 이미지 shape => (512, 512)
106번 이미지 shape => (512, 512)
107번 이미지 shape => (512, 512)
예외 발생! => 108번 이미지 없음
109번 이미지 shape => (512, 512)
110번 이미지 shape => (512, 512)
111번 이미지 shape => (512, 512)
112번 이미지 shape => (512, 512)
113번 이미지 shape => (512, 512)
114번 이미지 shape => (512, 512)
115번 이미지 shape => (512, 512)
116번 이미지 shape => (512, 512)
예외 발생! => 117번 이미지 없음
118번 이미지 shape => (512, 512)
119번 이미지 shape => (512, 512)
120번 이미지 shape => (512, 512)
121번 이미지 shape => (512, 512)
122번 이미지 shape => (512, 512)
123번 이미지 shape => (512, 512)
124번 이미지 shape => (512, 512)
125번 이미지 shape => (512, 512)
예외 발생! => 126번 이미지 없음
127번 이미지 shape => (512, 512)
128번 이미지 shape => (512, 512)
129번 이미지 shape => (512, 512)
130번 이미지 shape => (512, 512)
131번 이미지 shape => (512, 512)
132번 이미지 shape => (512, 512)
133번 이미지 shape => (512, 512)
134번 이미지 shape => (512, 512)
135번 이

In [ ]:
# print(len(no_file_num))

111


In [ ]:
img = Image.open('C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_000002.jpg').convert('L')
pix = np.array(img)
x = np.array(img)
print(x.shape)
print(x)

(512, 512)
[[165 163 161 ... 104 104 104]
 [165 163 161 ... 104 104 104]
 [165 163 161 ... 104 104 104]
 ...
 [158 157 157 ...  91  90  90]
 [156 155 155 ...  92  92  92]
 [155 154 155 ...  93  93  93]]


In [ ]:
total_list = []   # 모든 이미지 파일들의 픽셀값을 담은 리스트를 모두 담은 리스트
list = []  # 1개의 이미지 파일에 대한 픽셀값
count = 1
for first in range(len(x)):
    # print(f"----- {count} ------")
    # print(x[first])
    # count +=1
    for value in range(len(x[first])):
        list.append(x[first][value])

In [ ]:
total_list = []   # 모든 이미지 파일들의 픽셀값을 담은 리스트를 모두 담은 리스트

# no_file_num
for i in range(2, 10):
    if i not in no_file_num:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_00000{i}.jpg').convert('L')
        pix = np.array(img)
        x = np.array(img)

        list = []  # 1개의 이미지 파일에 대한 픽셀값
        for first in range(len(x)):
            for value in range(len(x[first])):
                list.append(x[first][value])
        total_list.append(list)
print(len(total_list))

7


In [ ]:
for i in range(10, 100):
    if i not in no_file_num:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_0000{i}.jpg').convert('L')
        pix = np.array(img)
        x = np.array(img)

        list = []  # 1개의 이미지 파일에 대한 픽셀값
        for first in range(len(x)):
            for value in range(len(x[first])):
                list.append(x[first][value])
        total_list.append(list)
print(len(total_list))

88


In [ ]:
for i in range(100, 400):
    if i not in no_file_num:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_000{i}.jpg').convert('L')
        pix = np.array(img)
        x = np.array(img)

        list = []  # 1개의 이미지 파일에 대한 픽셀값
        for first in range(len(x)):
            for value in range(len(x[first])):
                list.append(x[first][value])
        total_list.append(list)
print(len(total_list))

NameError: name 'no_file_num' is not defined

In [ ]:
# Memory Error 발생!!!!!!

# for i in range(100, 1010):
#     if i not in no_file_num:
#         img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_000{i}.jpg').convert('L')
#         pix = np.array(img)
#         x = np.array(img)

#         list = []  # 1개의 이미지 파일에 대한 픽셀값
#         for first in range(len(x)):
#             for value in range(len(x[first])):
#                 list.append(x[first][value])
#         total_list.append(list)
# print(len(total_list))

In [ ]:
col_list = []
for i in range(1,262145):
    col_list.append(f"pixel{i}")
    
print(col_list[-5:])

In [ ]:
dataframe = pd.DataFrame(total_list, col_list)
dataframe.head()