In [15]:
import torch
import torch.nn as nn
from torchinfo import summary

In [16]:
class Net(nn.Module):
    
    # 모델 구성 요소 생성 및 구조 설정
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(8, 4)
        self.fc2 = nn.Linear(4, 2)
        self.drop = nn.Dropout(0.5)
        self.fc3 = nn.Linear(2, 1)
        
    # 순방향 학습 진행 함수
    def forward(self, x):
        return self.fc3(self.fc2(self.fc1(x)))

In [17]:
## 모델 인스턴스 생성
model = Net()
print(model)

Net(
  (fc1): Linear(in_features=8, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=2, bias=True)
  (fc3): Linear(in_features=2, out_features=1, bias=True)
)


In [27]:
summary(model)

Layer (type:depth-idx)                   Param #
Net                                      --
├─Linear: 1-1                            36
├─Linear: 1-2                            10
├─Linear: 1-3                            3
Total params: 49
Trainable params: 49
Non-trainable params: 0

In [29]:
'''
위의 summary 했을때 return 값 설명

w + b
8 + 1
8 + 1
8 + 1
8 + 1
===> total 36

4 + 1
4 + 1
===> total 10

2 + 1
===> total 3
'''

'\n아래 return 값 설명\n\nw + b\n8 + 1\n8 + 1\n8 + 1\n8 + 1\n===> total 36\n\n4 + 1\n4 + 1\n===> total 10\n\n2 + 1\n===> total 3\n'

In [19]:
# 모델 인스턴스 속성 확인
model.fc1

Linear(in_features=8, out_features=4, bias=True)

In [20]:
# 모델의 특정 층 추출
model.fc1.weight, model.fc1.bias

(Parameter containing:
 tensor([[-0.1255,  0.1422,  0.2981,  0.1013,  0.2921, -0.2534,  0.2406, -0.1054],
         [-0.0361,  0.2855, -0.1276, -0.2653,  0.1075, -0.2423, -0.1195, -0.3325],
         [-0.2894, -0.0829,  0.1107, -0.2158, -0.1197,  0.2339,  0.2296,  0.1411],
         [-0.3002,  0.2563, -0.0595,  0.0604, -0.0935,  0.1311, -0.0607,  0.2935]],
        requires_grad=True),
 Parameter containing:
 tensor([0.2019, 0.1609, 0.3325, 0.1518], requires_grad=True))

In [21]:
# 모델의 각 층별 w,b 텐서 정보 확인
for param in model.parameters():    # 파라미터 값만 준다.
    print(param, end = '\n\n')

Parameter containing:
tensor([[-0.1255,  0.1422,  0.2981,  0.1013,  0.2921, -0.2534,  0.2406, -0.1054],
        [-0.0361,  0.2855, -0.1276, -0.2653,  0.1075, -0.2423, -0.1195, -0.3325],
        [-0.2894, -0.0829,  0.1107, -0.2158, -0.1197,  0.2339,  0.2296,  0.1411],
        [-0.3002,  0.2563, -0.0595,  0.0604, -0.0935,  0.1311, -0.0607,  0.2935]],
       requires_grad=True)

Parameter containing:
tensor([0.2019, 0.1609, 0.3325, 0.1518], requires_grad=True)

Parameter containing:
tensor([[-0.2247,  0.4402,  0.0838, -0.4807],
        [-0.0590, -0.0801, -0.1208, -0.3726]], requires_grad=True)

Parameter containing:
tensor([-0.4060, -0.3793], requires_grad=True)

Parameter containing:
tensor([[-0.0326,  0.0343]], requires_grad=True)

Parameter containing:
tensor([0.0494], requires_grad=True)


In [22]:
for param in model.named_parameters():   # 파라미터 값과 이름을 같이 준다.
    print(param, end = '\n\n')

('fc1.weight', Parameter containing:
tensor([[-0.1255,  0.1422,  0.2981,  0.1013,  0.2921, -0.2534,  0.2406, -0.1054],
        [-0.0361,  0.2855, -0.1276, -0.2653,  0.1075, -0.2423, -0.1195, -0.3325],
        [-0.2894, -0.0829,  0.1107, -0.2158, -0.1197,  0.2339,  0.2296,  0.1411],
        [-0.3002,  0.2563, -0.0595,  0.0604, -0.0935,  0.1311, -0.0607,  0.2935]],
       requires_grad=True))

('fc1.bias', Parameter containing:
tensor([0.2019, 0.1609, 0.3325, 0.1518], requires_grad=True))

('fc2.weight', Parameter containing:
tensor([[-0.2247,  0.4402,  0.0838, -0.4807],
        [-0.0590, -0.0801, -0.1208, -0.3726]], requires_grad=True))

('fc2.bias', Parameter containing:
tensor([-0.4060, -0.3793], requires_grad=True))

('fc3.weight', Parameter containing:
tensor([[-0.0326,  0.0343]], requires_grad=True))

('fc3.bias', Parameter containing:
tensor([0.0494], requires_grad=True))


In [23]:
# 모델 구성 모든 layer 가져오기
for child in model.children():       # 층 정보만 가져옴
    print(child, end = '\n\n')

Linear(in_features=8, out_features=4, bias=True)

Linear(in_features=4, out_features=2, bias=True)

Linear(in_features=2, out_features=1, bias=True)


In [24]:
for child in model.named_children():   #이름과 함께 층 정보를 가져옴
    print(child, end = '\n\n')

('fc1', Linear(in_features=8, out_features=4, bias=True))

('fc2', Linear(in_features=4, out_features=2, bias=True))

('fc3', Linear(in_features=2, out_features=1, bias=True))


- Layer의 가중치 설정

In [25]:
# 세비어 알고리즘의 가중치 초기화
nn.init.xavier_uniform_(model.fc1.weight)

# 함수뒤에 언더바 붙은거는 inplace = True 이다. (원본에 적용)

Parameter containing:
tensor([[-0.6466,  0.2391, -0.2211,  0.5777,  0.7017,  0.2388, -0.3550,  0.4785],
        [-0.4795, -0.0828,  0.6602,  0.5417, -0.0509, -0.6673, -0.2891, -0.1325],
        [ 0.6378, -0.2741, -0.5575, -0.5780,  0.0655, -0.0257, -0.0338, -0.6246],
        [ 0.2296, -0.1085,  0.2511,  0.5390,  0.6288, -0.6997, -0.6201,  0.1470]],
       requires_grad=True)

In [26]:
# 헤 알고리즘의 가중치 초기화
nn.init.kaiming_normal_(model.fc2.weight)

Parameter containing:
tensor([[ 0.7932, -0.6411, -0.1664,  0.5296],
        [-1.6455, -0.7969, -0.2835,  0.3261]], requires_grad=True)

+) uniform_과 normal_의 차이         
: uniform_은 균일 분포에서 랜덤하게 값을 뽑아내고, normal은 정규 분포에서 랜덤하게 값을 뽑아낸다.