### softmax(), sigmoid() 함수 <hr>
- sigmoid() : y = wx + b  결과 1개 전달 ===> 반환 : 0.0 ~ 1.0 사이 값으로 변환 ==> 이진분류
- softmax() : y = wx + b  결과 여러개 전달 ===> 반환 : 여러개의 결과값의 합이 1.0이 되도록 변환 ==> 다중븐류

In [12]:
# 모듈로딩
import torch                                     # 파이토치 기본 모듈로 텐서 및 기본 함수들
import torch.nn.functional as F                  # 파이토치 인공 신경망 관련 함수들 

In [13]:
# 임의의 데이터 생성
data1 = torch.tensor([1,2,1,1,2])
data1.shape

torch.Size([5])

In [14]:
F.sigmoid(data1)

# 원소단위로 들어가서 자동으로 값을 계산해줌

tensor([0.7311, 0.8808, 0.7311, 0.7311, 0.8808])

In [15]:
# data2 = data1.unsqueeze(dim=0)
data2 = data1.unsqueeze(dim=1)
data2.shape, data2

(torch.Size([5, 1]),
 tensor([[1],
         [2],
         [1],
         [1],
         [2]]))

softmax 이해를 위한 작은 예시

In [16]:
input = torch.randn(2, 3)
input

tensor([[ 0.6965,  1.0012,  2.2343],
        [ 0.0248,  0.8066, -1.0543]])

In [17]:
output = F.softmax(input)
output

# 1개의 행의 합이 1.0이 되도록 값을 바꿔준다.
# 입력받은 값을 출력으로 0~1사이의 값으로 모두 정규화하며 출력 값들의 총합은 항상 1이 되는 특성을 가진 함수이다. 분류하고 싶은 클래수의 수 만큼 출력으로 구성한다.
# 가장 큰 출력 값을 부여받은 클래스가 확률이 가장 높은 것으로 이용된다.

C:\Users\kdp\AppData\Local\Temp\ipykernel_15736\3317666777.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output = F.softmax(input)


tensor([[0.1426, 0.1934, 0.6639],
        [0.2837, 0.6199, 0.0964]])

In [18]:
output.sum(dim=1)
# 각 행마다 합계가 1인 것을 확인할 수 있다.

tensor([1., 1.])

In [19]:
output.ndim

2

In [20]:
output.sum(dim = 0)

tensor([0.4263, 0.8134, 0.7603])

In [21]:
output.max()

tensor(0.6639)

In [27]:
output.max(dim = 0)

torch.return_types.max(
values=tensor([0.2837, 0.6199, 0.6639]),
indices=tensor([1, 1, 0]))

In [22]:
output.max(dim = 1)
# 행마다 가장 큰 값이 뭐고 그 큰값에 대한 인덱스가 무언인지 알려준다.

torch.return_types.max(
values=tensor([0.6639, 0.6199]),
indices=tensor([2, 1]))

In [29]:
print(output.max(dim = 1)[1], output.max(dim = 1)[1][0], output.max(dim = 1)[1][0].item(), sep = '\n')

tensor([2, 1])
tensor(2)
2


In [23]:
output.max(dim = 1)[1]

tensor([2, 1])

In [24]:
output.max(dim = 1)[1][0]

tensor(2)

In [25]:
output.max(dim = 1)[1][0].item()

2

In [26]:
output.argmax(dim=1)
# 값은 없고 인덱스만 주는 것

tensor([2, 1])