### 인공신경망 모델 클래스 만들기 <hr>
- 부모 클래스 : nn.Module 상속 받음
- 필수 오버라이딩 메서드 : __init__(), forward()

[1] 모듈 로딩 <hr>

In [1]:
import torch
import torch.nn as nn

In [21]:
# 로지스틱회귀 모델 클래스 생성
# - Linear + sigmoid

class LogicLinear(nn.Module):
    
    # 모델 구조 설정
    def __init__(self, in_, out_):
        super().__init__()
        self.layer1 = nn.Linear(in_, 10)
        self.sigmoid1 = nn.Sigmoid()        
        self.layer2 = nn.Linear(10, out_)
        self.sigmoid2 = nn.Sigmoid()
        
    # 순방향 학습 진행 콜백함수
    def forward(self, x):
        y = self.layer1(x)
        z = self.sigmoid1(y)
        y = self.layer2(z)
        z = self.sigmoid2(y)
        return y

In [24]:
ll = LogicLinear(1, 4)
print(f"모델 구조 확인 ==> \n{ll}")

모델 구조 확인 ==> 
LogicLinear(
  (layer1): Linear(in_features=1, out_features=10, bias=True)
  (sigmoid1): Sigmoid()
  (layer2): Linear(in_features=10, out_features=4, bias=True)
  (sigmoid2): Sigmoid()
)


In [25]:
print('모델 구성 w, b =====\n')
for param in ll.parameters():
    print(param)
    print()

모델 구성 w, b =====

Parameter containing:
tensor([[ 0.1845],
        [-0.1361],
        [-0.7209],
        [-0.5637],
        [ 0.8158],
        [ 0.1968],
        [ 0.1644],
        [ 0.1087],
        [-0.3603],
        [ 0.8999]], requires_grad=True)

Parameter containing:
tensor([-0.6833,  0.5729, -0.2817, -0.6439, -0.2878, -0.1991,  0.4061,  0.0636,
        -0.2799,  0.7743], requires_grad=True)

Parameter containing:
tensor([[ 0.2303, -0.0492, -0.1516,  0.1350, -0.2776, -0.2709,  0.0030, -0.3018,
          0.1926, -0.3052],
        [-0.1395,  0.2956, -0.1200,  0.3045, -0.2749,  0.0490, -0.3125, -0.1576,
         -0.0728, -0.3133],
        [-0.0508,  0.1283,  0.1018, -0.3105,  0.2348,  0.1317,  0.2650, -0.0074,
          0.1859,  0.2279],
        [ 0.2794, -0.1566,  0.1797,  0.1120, -0.2844,  0.0099,  0.1308, -0.1262,
         -0.2151, -0.1830]], requires_grad=True)

Parameter containing:
tensor([-0.1684,  0.0147, -0.1295,  0.0099], requires_grad=True)
