### 텐서(Tensor) 살펴보기
- Pytorch에서 데이터 저장 자료형
- 모델 입력 (input), 출력(output) 데이터 형태
- 얘는 쓸때 텐서로 하나하나씩 다 바꿔주고 사용해야함

- 모듈 로딩

In [205]:
import torch

- Tensor 속성 관련 함수

In [206]:
# 매개변수 : 텐서 인스턴스, 텐서 변수명
def print_attribute(tensor, name):
    print(f"[Tensor {name}\'s Attribute]")
    print(f" - tensor.shape : {tensor.shape}")
    print(f" - tensor.ndim : {tensor.ndim}D")
    print(f" - tensor.dtype : {tensor.dtype}")
    print(f" - tensor.device : {tensor.device}")
    print(f" - tensor.requires_grad : {tensor.requires_grad}")
    print(f" - tensor.data : \n   {tensor.data}")

- Tensor 생성 (1) 특정 데이터 타입의 텐서 생성
    * 타입별 텐서 클래스 생성자 활용
    * 예) IntTensor(), FloatTensor(), BoolTensor()

In [207]:
# 정수 타입 텐서 생성
t1 = torch.IntTensor(10)
print_attribute(t1, 't1')

[Tensor t1's Attribute]
 - tensor.shape : torch.Size([10])
 - tensor.ndim : 1D
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
   tensor([ 1073741824,  1070751501,           0,  1067792890,           0,
         1067931250,           0,  1069432977, -2147483648,  1071840281],
       dtype=torch.int32)


In [208]:
# 정수 타입 텐서 생성
t2 = torch.IntTensor([10., 20.])
print_attribute(t2, 't2')
# float으로 들어갔지만 int Tensor를 만들었기 때문에 결국 int가 된다.
# warning : 만약 소수점 이하에서 숫자들이 있었다면 처리 과정에서 데이터 손실이 있으니 쓰지말라고 경고하는,,~

[Tensor t2's Attribute]
 - tensor.shape : torch.Size([2])
 - tensor.ndim : 1D
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
   tensor([10, 20], dtype=torch.int32)


C:\Users\kdp\AppData\Local\Temp\ipykernel_3448\3487941296.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t2 = torch.IntTensor([10., 20.])


In [209]:
# 불 타입 텐서 생성
t3 = torch.BoolTensor([1, 1, 0, -1])
print_attribute(t3, 't3')

[Tensor t3's Attribute]
 - tensor.shape : torch.Size([4])
 - tensor.ndim : 1D
 - tensor.dtype : torch.bool
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
   tensor([ True,  True, False,  True])


In [210]:
# 실수 타입 텐서 생성
t4 = torch.FloatTensor([10, 20])
print_attribute(t4, 't4')

[Tensor t4's Attribute]
 - tensor.shape : torch.Size([2])
 - tensor.ndim : 1D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
   tensor([10., 20.])


- Tensor 생성 (2) 원하는 값으로 텐서 생성 => torch.tensor()

In [211]:
t1 = torch.tensor(10)   # scalar 데이터, int64
print_attribute(t1, 't1')

[Tensor t1's Attribute]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.int64
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
   10


In [212]:
t1 #scalar라는 거이고 대괄호 없이 넣어서 아예 차원이 없다. 차원이라는 것은 축이 생겨야 한다. 1D면 축이 1개, 2D면 축이 2개, 3D면 축이 3개 ... 근데 이거는 축이 없다는거!

tensor(10)

In [213]:
t2 = torch.tensor(10.0)   # scalar 데이터, float32
print_attribute(t2, 't2')

[Tensor t2's Attribute]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
   10.0


In [214]:
t3 = torch.tensor(10., dtype = torch.int32)   # scalar 데이터, int32
print_attribute(t3, 't3')

[Tensor t3's Attribute]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
   10


C:\Users\kdp\AppData\Local\Temp\ipykernel_3448\387580399.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t3 = torch.tensor(10., dtype = torch.int32)   # scalar 데이터, int32


In [215]:
# dtype 매개변수 : 원하는 데이터 타입 지정 가능
t4 = torch.tensor(10., dtype = torch.bool)   # scalar 데이터, bool
print_attribute(t4, 't4')

[Tensor t4's Attribute]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.bool
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
   True


In [216]:
t5 = torch.tensor([1,2,3], dtype = torch.int8)   # 1D 데이터
print_attribute(t5, 't5')

[Tensor t5's Attribute]
 - tensor.shape : torch.Size([3])
 - tensor.ndim : 1D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
   tensor([1, 2, 3], dtype=torch.int8)


In [217]:
t6 = torch.tensor([[1,2,3]], dtype = torch.int8)   # 2D 데이터
print_attribute(t6, 't6')

[Tensor t6's Attribute]
 - tensor.shape : torch.Size([1, 3])
 - tensor.ndim : 2D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
   tensor([[1, 2, 3]], dtype=torch.int8)


- 특정 값으로 생성 (3) 특정 값으로 채운 텐서 => 0, 1 등의 값

In [218]:
# 0으로 채운 텐서
t1 = torch.zeros(5)
print_attribute(t1, 't1')    # 5개가 채워진 것을 알 수 있다.

[Tensor t1's Attribute]
 - tensor.shape : torch.Size([5])
 - tensor.ndim : 1D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
   tensor([0., 0., 0., 0., 0.])


In [219]:
# 0으로 채운 텐서
t1 = torch.zeros((5,5))
print_attribute(t1, 't1') 

[Tensor t1's Attribute]
 - tensor.shape : torch.Size([5, 5])
 - tensor.ndim : 2D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
   tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [220]:
# 1으로 채운 텐서
t1 = torch.ones((2,4), dtype = torch.int8)
print_attribute(t1, 't1')

[Tensor t1's Attribute]
 - tensor.shape : torch.Size([2, 4])
 - tensor.ndim : 2D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
   tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int8)


In [221]:
# 이미 존재하는 텐서와 동일한 shape으로 잡고 값 채우기 => zeros_like(), ones_like()
img = torch.tensor([[2,3,4,5,6,7], [2,3,4,5,6,7]])
print(img.shape)

torch.Size([2, 6])


In [222]:
zero_img = torch.zeros_like(img)
print(zero_img)                      # 똑같은 shape 인데 0으로 채웠다.

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])


In [223]:
one_img = torch.ones_like(img)
print(one_img)                       # 똑같은 shape 인데 1으로 채웠다.

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])


In [224]:
full_img = torch.full_like(img,7)
print(full_img)                       # 똑같은 shape 인데 7으로 채웠다.

tensor([[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]])


In [225]:
# 대각선 방향으로 1 채우기 => eye()
t1 = torch.eye(5)
print(t1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


- Tensor 생성 방법 (4) : 임의의 값으로 Tensor 생성 => torch.rand(), torch.randn(), torch.randint()

In [226]:
torch.manual_seed(12)   # 랟덤 초기값 설정
t1 = torch.rand(2,3)    # [0,1) 분포 안에서 랜덤 생성
print(t1)
t2 = torch.randn(2,3)   # standard normal 분포안에서 랜덤 생성
print(t2)
t3 = torch.randint(low=1, high=10, size = (2,3))    # low <= 값 < high
print(t3)

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])
tensor([[ 1.5869,  1.1268, -1.2274],
        [-0.8216, -1.7861,  0.6167]])
tensor([[8, 4, 6],
        [2, 2, 2]])


- Tensor 생성 방법 (5) : Ndarray 객체 활용 => torch.from_numpy(), torch.as_tensor(), tensor()

In [227]:
# 데이터 생성
import numpy as np

data = np.array([11, 22, 33])
print(data, type(data))

[11 22 33] <class 'numpy.ndarray'>


In [228]:
t1 = torch.from_numpy(data)
print(t1)

tensor([11, 22, 33], dtype=torch.int32)


In [229]:
t2 = torch.as_tensor(data)
print(t2)

tensor([11, 22, 33], dtype=torch.int32)


In [230]:
t3 = torch.tensor(data)
print(t3)

tensor([11, 22, 33], dtype=torch.int32)


In [231]:
# ndarray 원소 변경
data[0] = 100

In [232]:
# from_numpy(), as_tensor() ==> 데이터 공유
# tensor()    ==> 복사본 생성
print(data, t1, t2, t3, sep = '\n')

[100  22  33]
tensor([100,  22,  33], dtype=torch.int32)
tensor([100,  22,  33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)
