### Tensor 원소/요소 접근
- 인덱싱과 슬라이싱

In [43]:
# 모듈 로딩
import torch

In [54]:
# 텐서 생성
points = torch.tensor([[4., 2.], [5., 3.], [6., 4.]], dtype = torch.int16)
print(points)

tensor([[4, 2],
        [5, 3],
        [6, 4]], dtype=torch.int16)


C:\Users\kdp\AppData\Local\Temp\ipykernel_13440\1574475049.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  points = torch.tensor([[4., 2.], [5., 3.], [6., 4.]], dtype = torch.int16)


In [45]:
# 텐서의 원소 1개 접근
# 데이터 3 추출
print(points[1,1])

# 마지막 데이터 4 추출
print(points[2,1], points[-1,1])

tensor(3, dtype=torch.int16)
tensor(4, dtype=torch.int16) tensor(4, dtype=torch.int16)


In [46]:
# 1번 행부터 나머지 모든 행 추출
print(points[1:])

tensor([[5, 3],
        [6, 4]], dtype=torch.int16)


In [47]:
t1 = torch.rand(2, 3, 1)    # 3D
t1

tensor([[[0.0873],
         [0.2638],
         [0.4621]],

        [[0.5733],
         [0.2127],
         [0.7367]]])

In [48]:
t1 = torch.rand(2,3,2,3)    # 4D
t1

tensor([[[[0.9125, 0.2087, 0.6867],
          [0.8117, 0.1469, 0.6113]],

         [[0.5073, 0.0258, 0.1775],
          [0.6494, 0.9284, 0.7112]],

         [[0.8201, 0.2100, 0.5035],
          [0.5501, 0.7126, 0.7348]]],


        [[[0.9924, 0.6147, 0.7691],
          [0.7750, 0.3406, 0.6642]],

         [[0.5622, 0.7608, 0.6566],
          [0.1940, 0.3289, 0.2283]],

         [[0.2207, 0.2693, 0.1146],
          [0.1957, 0.8430, 0.6205]]]])

- 브로드캐스팅 연산

In [49]:
m1 = torch.FloatTensor([[1,2]])    # shape => (1,2)
m2 = torch.FloatTensor([3])        # shape => (1,1)
print(f"m1.shape => {m1.shape}   m2.shape => {m2.shape}\n")
m3 = m1 + m2
print(f"{m3} \nm3.shape :{m3.shape}")

m1.shape => torch.Size([1, 2])   m2.shape => torch.Size([1])

tensor([[4., 5.]]) 
m3.shape :torch.Size([1, 2])


In [50]:
m1 = torch.FloatTensor([[1,2]])    # shape => (1,2)
m2 = torch.FloatTensor([[3],[4]])  # shape => (2,1)
print(f"m1.shape => {m1.shape}   m2.shape => {m2.shape}\n")
m3 = m1 + m2
print(f"{m3} \nm3.shape :{m3.shape}")

m1.shape => torch.Size([1, 2])   m2.shape => torch.Size([2, 1])

tensor([[4., 5.],
        [5., 6.]]) 
m3.shape :torch.Size([2, 2])


In [51]:
m1 = torch.FloatTensor([[1,2]])    # shape => (1,2)
m2 = torch.FloatTensor([[3],[4]])  # shape => (2,1)
print(f"m1.shape => {m1.shape} \nm2.shape => {m2.shape}\n")
m3 = m1 * m2
print(f"{m3} \nm3.shape :{m3.shape}")

m1.shape => torch.Size([1, 2]) 
m2.shape => torch.Size([2, 1])

tensor([[3., 6.],
        [4., 8.]]) 
m3.shape :torch.Size([2, 2])


In [53]:
# 원소 단위 연산 수행 메서드
m4 = m1.add(m2)
print(f"{m3} \nm3.shape :{m3.shape}\n")
m4 = m1.sub(m2)
print(f"{m3} \nm3.shape :{m3.shape}\n")
m4 = m1.mul(m2)
print(f"{m3} \nm3.shape :{m3.shape}\n")
m4 = m1.div(m2)
print(f"{m3} \nm3.shape :{m3.shape}\n")

# 직접 연산하지 않고 메서드를 사용했다.

tensor([[3., 6.],
        [4., 8.]]) 
m3.shape :torch.Size([2, 2])

tensor([[3., 6.],
        [4., 8.]]) 
m3.shape :torch.Size([2, 2])

tensor([[3., 6.],
        [4., 8.]]) 
m3.shape :torch.Size([2, 2])

tensor([[3., 6.],
        [4., 8.]]) 
m3.shape :torch.Size([2, 2])
