## 행렬 곱셈
- 피처와 가중치 연산에 활용
- tensor.matmul()

In [17]:
# 모듈 로딩
import torch

In [18]:
data = torch.tensor([[1, 2],
                     [3, 4]])
w = torch.tensor([7])

In [19]:
print(f"data.shape => {data.shape}")
print(f"w.shape => {w.shape}")

data.shape => torch.Size([2, 2])
w.shape => torch.Size([1])


In [20]:
# 원소 단위 곱셈 => 인덱스에 1:1 대응하도록 브로드 캐스팅
print(f" {data.mul(w)}")

 tensor([[ 7, 14],
        [21, 28]])


In [24]:
# 행열단위 곱셈 => 행 X 열 : (행, 열) X (원소수)
w = torch.tensor([7, 8])
print(data.shape, w.shape)
print(w.ndim)
print(f"data.matmul(w) : {data.matmul(w)}")
print(data.mul(w))

torch.Size([2, 2]) torch.Size([2])
1
data.matmul(w) : tensor([23, 53])
tensor([[ 7, 16],
        [21, 32]])


In [25]:
# 행열단위 곱셈 => 행 X 열 : (행, 열) X (행, 열)
w2 = torch.tensor([[7], [8]])
print(data.shape, w2.shape)
print(w2.ndim)
print(f"data.matmul(w2) \n {data.matmul(w2)}")

torch.Size([2, 2]) torch.Size([2, 1])
2
data.matmul(w2) 
 tensor([[23],
        [53]])


In [27]:
w3 = torch.tensor([[11, 22], [33, 44]])
print(w3)
print(w3.shape)
print(data.matmul(w3))

tensor([[11, 22],
        [33, 44]])
torch.Size([2, 2])
tensor([[ 77, 110],
        [165, 242]])
