### Tensor shape 변경
- reshape(), view() : 원소 갯수가 유지됨!, 기존 텐서 공유함

In [129]:
# 모듈 로딩
import torch

In [130]:
# 텐서 데이터 생성
t1 = torch.tensor([[1,2,3], [4,5,6]])      # 원소개수는 6개임
print(t1.shape, t1.ndim)
print(t1)

torch.Size([2, 3]) 2
tensor([[1, 2, 3],
        [4, 5, 6]])


In [131]:
# [2, 3] ====> [3, 2] 형태 변경 : 원소 동일 6개
t1.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [132]:
# [2, 3] ====> [6, 1] 형태 변경 : 원소 동일 6개
t1.view(6, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [133]:
# [2, 3] ====> [6, 1] 형태 변경 : 원소 동일 6개
# -1 : 원소 수를 알아서 할당
t1.view(-1,1)     # 여기서 -1은 인덱스 번호가 아니고 난 몰겟슴! 니가 알아서 하고 열만 1개로 해놓으셈 ! 이거임

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [134]:
t1.view(1, -1)  # 여기서 -1은 인덱스 번호가 아니고 난 몰겟슴! 니가 알아서 하고 행만 1개로 해놓으셈 ! 이거임

tensor([[1, 2, 3, 4, 5, 6]])

In [135]:
# tensor.reshape()
t1.reshape(6, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [136]:
t1.reshape(-1, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [137]:
# 원소 수 유지되어야 함!
# RuntimeError: shape '[-1, 7]' is invalid for input of size 6
# t1.reshape(-1, 7)

# 에러 발생! 원소는 6개 뿐이라,,

- 전치 : 열 <-> 행 변경

In [138]:
print(t1.shape)

t2 = t1.T
print(t2.shape, t2.is_contiguous())

torch.Size([2, 3])
torch.Size([3, 2]) False


In [139]:
# ERROR : RuntimeError: view size is not compatible with input tensor's size and stride 
# t2.view(-1, 6)

In [140]:
t3 = t2.reshape(-1, 6)
print(t3)
print(t3.is_contiguous())

tensor([[1, 4, 2, 5, 3, 6]])
True


### 텐서 데이터의 메모리 저장 정보 즉 메타데이터
- 현재 저장 형태, 검색 방향 정보, 시작 정보

In [141]:
t1 = torch.tensor([[1,2,3], [4,5,6]])
print(t1.shape, t1.ndim)
print(f"storage => \n{t1.storage()}")
print(f"storage_offset = > {t1.storage_offset()}")
print(f"stride => {t1.stride()}")                    # 다음 줄에 가려면 몇칸 가야하냐? 3칸이올시다!
print(f"is_contiguous => {t1.is_contiguous()}")      # 연속적이냐?

torch.Size([2, 3]) 2
storage => 
 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
storage_offset = > 0
stride => (3, 1)
is_contiguous => True


In [142]:
t2 = t1.reshape(-1, 2)
print(t2.shape, t2.ndim)
print(f"storage => \n{t2.storage()}")
print(f"storage_offset = > {t2.storage_offset()}")
print(f"stride => {t2.stride()}")                    # 다음 줄에 가려면 몇칸 가야하냐?
print(f"is_contiguous => {t2.is_contiguous()}")      # 연속적이냐?

torch.Size([3, 2]) 2
storage => 
 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
storage_offset = > 0
stride => (2, 1)
is_contiguous => True


In [143]:
t2 = t1.view(-1, 2)
print(t2.shape, t2.ndim)
print(f"storage => \n{t2.storage()}")
print(f"storage_offset = > {t2.storage_offset()}")
print(f"stride => {t2.stride()}")                    # 다음 줄에 가려면 몇칸 가야하냐?
print(f"is_contiguous => {t2.is_contiguous()}")      # 연속적이냐?

torch.Size([3, 2]) 2
storage => 
 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
storage_offset = > 0
stride => (2, 1)
is_contiguous => True


In [144]:
t2 = t1.T.view(-1, 2)
print(t2)
print(t2.shape, t2.ndim)
print(f"storage => \n{t2.storage()}")
print(f"storage_offset = > {t2.storage_offset()}")   # 시작 위치는 어디냐?
print(f"stride => {t2.stride()}")                    # 같은 행에 다음 열로 가려면 몇칸? 다음 행에 가려면 몇칸? 가야하냐?
print(f"is_contiguous => {t2.is_contiguous()}")      # 연속적이냐?  (여기서는 transpose 이기 때문에 불연속으로 됨)
t2 = t2.contiguous()
print(f"is_contiguous => {t2.is_contiguous()}")      # 연속적이냐?

tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2]) 2
storage => 
 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
storage_offset = > 0
stride => (1, 3)
is_contiguous => False
is_contiguous => True


In [145]:
t2 = t1.T.reshape(-1, 2)
print(t2)
print(t2.shape, t2.ndim)
print(f"storage => \n{t2.storage()}")
print(f"storage_offset = > {t2.storage_offset()}")   # 시작 위치는 어디냐?
print(f"stride => {t2.stride()}")                    # 같은 행에 다음 열로 가려면 몇칸? 다음 행에 가려면 몇칸? 가야하냐?
print(f"is_contiguous => {t2.is_contiguous()}")      # 연속적이냐?  (여기서는 transpose 이기 때문에 불연속으로 됨)
t2 = t2.contiguous()
print(f"is_contiguous => {t2.is_contiguous()}")      # 연속적이냐?

tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2]) 2
storage => 
 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
storage_offset = > 0
stride => (1, 3)
is_contiguous => False
is_contiguous => True


### 차원 제거/추가
- tensor.squeeze() : 텐서에서 차원이 1인 것 제거
- tensor.unsqueeze(dim) : 텐서에 차원이 1인것 추가

In [146]:
# 데이터 생성
t1 = torch.tensor([[1, 2], [3, 4]])
t2 = torch.tensor([[1,2,3,4]])
t3 = torch.tensor([[[1,2,3,4]]])

In [147]:
print(f"t1 => {t1.shape}, {t1.ndim}D, {t1.data_ptr()}")
print(f"t2 => {t2.shape}, {t2.ndim}D, {t2.data_ptr()}")
print(f"t3 => {t3.shape}, {t3.ndim}D, {t3.data_ptr()}")

t1 => torch.Size([2, 2]), 2D, 4938541368768
t2 => torch.Size([1, 4]), 2D, 4938541368832
t3 => torch.Size([1, 1, 4]), 3D, 4938541368960


In [148]:
t11 = t1.squeeze()
t22 = t2.squeeze()
t33 = t3.squeeze()
t44 = t3.squeeze(dim = 2)     #여기서 dim이란 차원을 말한다. 여기서는 세번쨰 차원이 된다.

print(f"t1 차원 축소 => {t11.shape}, {t11.ndim}D, {t11.data_ptr()}")
print(f"t2 차원 축소 => {t22.shape}, {t22.ndim}D, {t22.data_ptr()}")
print(f"t3 차원 축소 => {t33.shape}, {t33.ndim}D, {t33.data_ptr()}")
print(f"t3 차원 축소 (지정) => {t44.shape}, {t44.ndim}D, {t44.data_ptr()}")
# 무조건 줄이는게 아니가 shape을 쳤을때 1인 애를 줄인다. (즉 1차원인 넘을 없애겠다.) => 그래서 차원을 줄인다. 3차원에서 2차원으로, 4차원에서 3차원으로 ...

t44 = t3.squeeze(dim = [0,1])     #여기서 dim이란 차원을 말한다. 여기서는 1차원+2차원을 말한다.
print(f"t3 차원 축소 (지정) => {t44.shape}, {t44.ndim}D, {t44.data_ptr()}")

t1 차원 축소 => torch.Size([2, 2]), 2D, 4938541368768
t2 차원 축소 => torch.Size([4]), 1D, 4938541368832
t3 차원 축소 => torch.Size([4]), 1D, 4938541368960
t3 차원 축소 (지정) => torch.Size([1, 1, 4]), 3D, 4938541368960
t3 차원 축소 (지정) => torch.Size([4]), 1D, 4938541368960


1차원 : [데이터수]
2차원 : [데이터수, 피처]
3차원 : [데이터수, 채널수, 높이, 너비]

In [149]:
t = torch.tensor([[[[[[[[1,2,3,4]]]]]]]])
print(f"t => {t.shape}, {t.ndim}D")
tt = t.squeeze()
print(f"{tt.shape}, {tt.ndim}D")

t => torch.Size([1, 1, 1, 1, 1, 1, 1, 4]), 8D
torch.Size([4]), 1D


In [150]:
## 원소/요소 수 변경없이 1차원 증가 시키기 => torch.unsqueeze(dim)
print(f"t1 정보 => {t1.shape}, {t1.ndim}D, {t1.data_ptr()}, {t1.stride()}")

t1 정보 => torch.Size([2, 2]), 2D, 4938541368768, (2, 1)


In [151]:
t11 = t1.unsqueeze(dim = 0)
t22 = t1.unsqueeze(dim = -1)

print(f"t1 차원 추가 => {t11.shape}, {t11.ndim}D, {t11.data_ptr()}, {t11.stride()}")
print(f"t2 차원 추가 => {t22.shape}, {t22.ndim}D, {t22.data_ptr()}, {t22.stride()}")

t1 차원 추가 => torch.Size([1, 2, 2]), 3D, 4938541368768, (4, 2, 1)
t2 차원 추가 => torch.Size([2, 2, 1]), 3D, 4938541368768, (2, 1, 1)


# Tensor 차원/형태 변경

In [152]:
t1 = torch.tensor([[[1,2], [11,22], [44,55]]])

print(f"t1  => {t1.shape}, {t1.ndim}D")

t1  => torch.Size([1, 3, 2]), 3D


ㅇㅇ            
ㅇㅇ                  
ㅇㅇ           

In [153]:
# 2개의 차원을 변경하는 메서드
t11 = t1.transpose(0, 2)

print(f"t11  => {t11.shape}, {t11.ndim}D")      # 1차원과 3차원이 바뀌었다.

t11  => torch.Size([2, 3, 1]), 3D


ㅇ            
ㅇ                
ㅇ                 
=> 이렇게 생긴거 2장

In [154]:
# 모든 차원을 변경하는 메서드
t22 = t1.permute(1,2,0)
print(f"t22 => {t22.shape}, {t22.ndim}D")          # 싹~~~~~~~다 바꾸었다.

t22 => torch.Size([3, 2, 1]), 3D


In [155]:
print(t1.data_ptr(), t11.data_ptr(), t22.data_ptr() ) # 주소가 바뀌지 않고 그대로 유지 됨을 알수있다! 즉, 메타데이터가 바뀌었다는 것이당

4938541307200 4938541307200 4938541307200
