# 텐서 연결 & 결합

In [43]:
# 모듈 로딩
import torch

In [44]:
# 텐서 데이터 생성
torch.manual_seed(12)

# 임의의 0. ~ 1 사이의 실수
X = torch.rand(2, 10)
# 임의의 정수 : low <= ~ < high
y = torch.randint(0, 2, (10,))
y2 = torch.randint(0, 2, (2,10))

In [45]:
print(f"X => {X.shape} {X.ndim}D")
print(f"y => {y.shape} {y.ndim}D")
print(f"y2 => {y2.shape} {y2.ndim}D")

X => torch.Size([2, 10]) 2D
y => torch.Size([10]) 1D
y2 => torch.Size([2, 10]) 2D


In [48]:
# tensor 연결  :  cat([텐서1, 텐서2, ...])
# torch.cat((X,y), dim = 1)

# ERROR : Tensors must have same number of dimensions: got 2 and 1

In [49]:
xy1 = torch.cat((X,y2), dim = 1)
print(f"xy1 => {xy1.shape} {xy1.ndim}D")

xy1 => torch.Size([2, 20]) 2D


In [50]:
xy1 = torch.cat((X,y2), dim = 0)
print(f"xy1 => {xy1.shape} {xy1.ndim}D")

xy1 => torch.Size([4, 10]) 2D


In [51]:
xy1

tensor([[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421, 0.7312,
         0.7224],
        [0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262, 0.9790, 0.8443, 0.1256,
         0.4456],
        [1.0000, 1.0000, 0.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])

In [52]:
xy1.max(dim = 0)

torch.return_types.max(
values=tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9790, 0.8443, 0.7312,
        0.7224]),
indices=tensor([2, 2, 3, 2, 2, 3, 1, 1, 0, 0]))

In [53]:
xy1.max(dim = 1)

torch.return_types.max(
values=tensor([0.7312, 0.9790, 1.0000, 1.0000]),
indices=tensor([8, 6, 0, 2]))

In [54]:
max_value = xy1.max(dim=1)[0]
max_value

tensor([0.7312, 0.9790, 1.0000, 1.0000])

In [55]:
# 열 단위로 최대값 및 최대값의 인덱스
max_value = xy1.max(dim=0)[0]
max_index = xy1.max(dim=0)[1]
max_value, max_index

(tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9790, 0.8443, 0.7312,
         0.7224]),
 tensor([2, 2, 3, 2, 2, 3, 1, 1, 0, 0]))

In [56]:
# 행 단위로 최대값 및 최대값의 인덱스
max_value = xy1.max(dim=1)[0]
max_index = xy1.max(dim=1)[1]
max_value, max_index

(tensor([0.7312, 0.9790, 1.0000, 1.0000]), tensor([8, 6, 0, 2]))

In [57]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

torch.stack([x,y,z])

# stack은 행기준으로 쌓이는거다 그래서 아래 코드를 한것과 같은 결과를 나타낸다
# torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])