### 선형 모델 동작 살펴보기
- nn.Linear 클래스
- y= wx+b 공식으로 동작하는 선형회귀모델

In [499]:
# 모듈 로딩
import torch                        # 텐서, 기본 함수들
import torch.nn as nn               # 인공신경망 관련
import torch.nn.functional as F        # 함수들

In [500]:
# 테스트용 임의의 데이터
data = torch.FloatTensor([[8,9], 
                          [6,6],
                          [3,4]])
target = torch.LongTensor([[17], [12], [7]])

data.shape, target.shape

(torch.Size([3, 2]), torch.Size([3, 1]))

In [501]:
# 선형모델 인스턴스 생성. => 각 입력 데이터의 피처 개수, 각 출력 데이터의 피처 개수
linear = nn.Linear(2,1) # 지금 하는 건 층이 없는 거 

In [502]:
# 학습 
output = linear(data)

print(f'[학습결과]\n{output.shape}\n{output}')

[학습결과]
torch.Size([3, 1])
tensor([[-2.7827],
        [-1.9259],
        [-1.0362]], grad_fn=<AddmmBackward0>)


In [503]:
## 모델 파라미터
linear.weight

Parameter containing:
tensor([[-0.1912, -0.1581]], requires_grad=True)

In [504]:
# 위의 모델 파라미터에서 단계적으로 값만 뽑아보자
print(linear.weight[0], linear.weight[0][0], linear.weight[0][0].item(), sep = '\n\n')

tensor([-0.1912, -0.1581], grad_fn=<SelectBackward0>)

tensor(-0.1912, grad_fn=<SelectBackward0>)

-0.19116824865341187


In [505]:
linear.bias

Parameter containing:
tensor([0.1699], requires_grad=True)

In [506]:
for i, value in enumerate(output.data) :
    print(f'[{i}] {output.data}')

[0] tensor([[-2.7827],
        [-1.9259],
        [-1.0362]])
[1] tensor([[-2.7827],
        [-1.9259],
        [-1.0362]])
[2] tensor([[-2.7827],
        [-1.9259],
        [-1.0362]])


In [507]:
for i, value in enumerate(output.data) :
    print(f'[{i}] {output.data[i].item()}')

[0] -2.782702684402466
[1] -1.9259448051452637
[2] -1.0361590385437012


In [508]:
# 선형식   (data에서 1행의 값을 선형식에 적용시켜보자)
y = linear.weight[0][0].item()*8. + linear.weight[0][1].item()*9 + linear.bias[0].item()
y

-2.7827027440071106

In [509]:
# 위에 처럼 담을 수도 있지만 이렇게 변수 지정해서는 가능하다
w1 = linear.weight[0][0].item()
w2 = linear.weight[0][1].item()
b = linear.bias[0].item()

y = w2 * 8. + w2 * 9. + b
y

-2.518480598926544

#### linear 결과와 활성화 함수
- 인공신경망에서 전결합층에 해당하는 Linear 모델에 AF 함수 적용

In [510]:
# 활성화 함수 (AF) 적용 - sigmoid
# sigmoid 함수 => 0.0 ~ 1.0 범위의 값으로 변환
af = F.sigmoid(output)
print(af)

# sigmoid를 거치면 0.0 ~ 1.0 사이의 값이 나온다.
# 그 결과에 대해서 0.5가 넘으면 0.5보다 크면 1, 0.5보다 작으면 0으로 결정해주는 거는 직접 해주어야한다.

tensor([[0.0583],
        [0.1272],
        [0.2619]], grad_fn=<SigmoidBackward0>)


In [511]:
# 활성화 함수 (AF) 적용 - relu
# relu 함수 => 값 > 0 : 그대로,   값 <= 0 : 0
af = F.relu(output)
print(af)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<ReluBackward0>)
