In [31]:
import torch
import torch.nn.functional as F
import torch.optim as optim

In [32]:
a = torch.IntTensor(10)
b = torch.tensor(2., requires_grad=True)

In [33]:
print('a tensor')
print(a.ndim, a.shape, a.requires_grad, a.grad, a.is_leaf, a.grad_fn)

a tensor
1 torch.Size([10]) False None True None


In [34]:
print('b tensor')
print(b.ndim, b.shape, b.requires_grad, b.grad, b.is_leaf, b.grad_fn)

b tensor
0 torch.Size([]) True None True None


In [35]:
c = a.mul(b)

In [36]:
print('c tensor')
print(c.ndim, c.shape, c.requires_grad, c.grad, c.is_leaf, c.grad_fn)

c tensor
1 torch.Size([10]) True None False <MulBackward0 object at 0x000001C5FF744700>


C:\Users\kdp\AppData\Local\Temp\ipykernel_8588\2044598097.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\b\abs_6fueooay2f\croot\pytorch-select_1707342446212\work\build\aten\src\ATen/core/TensorBody.h:494.)
  print(c.ndim, c.shape, c.requires_grad, c.grad, c.is_leaf, c.grad_fn)


- backward 전후로 어떻게 변화했는지 살펴보자능

In [42]:
x = torch.ones(5) # input tensor
y = torch.zeros(3) #expected output
w = torch.randn(5,3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
#loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

y2 = torch.zeros(1)
w2 = torch.randn(3, requires_grad=True)
b2 = torch.randn(1, requires_grad=True)
z2 = torch.matmul(z,w2)+b2
#x2 = torch.tensor((5, 5), z) # input tensor

#print(z, z.shape, w.shape)

loss = torch.nn.functional.binary_cross_entropy_with_logits(z2, y2)

In [43]:
print('x tensor', f'{x.shape}, {x.ndim}, {x.requires_grad}, {x.grad}, {x.is_leaf}, {x.grad_fn}')
print('y tensor', f'{y.shape}, {y.ndim}, {y.requires_grad}, {y.grad}, {y.is_leaf}, {y.grad_fn}')
print('w tensor', f'{w.shape}, {w.ndim}, {w.requires_grad}, {w.grad}, {w.is_leaf}, {w.grad_fn}')
print('b tensor', f'{b.shape}, {b.ndim}, {b.requires_grad}, {b.grad}, {b.is_leaf}, {b.grad_fn}')
print('z tensor', f'{z.shape}, {z.ndim}, {z.requires_grad}, {z.grad}, {z.is_leaf}, {z.grad_fn}')
print()
#print('x2 tensor', f'{x.shape}, {x.ndim}, {x.requires_grad}, {x.grad}, {x.is_leaf}, {x.grad_fn}')
print('y2 tensor', f'{y2.shape}, {y2.ndim}, {y2.requires_grad}, {y2.grad}, {y2.is_leaf}, {y2.grad_fn}')
print('w2 tensor', f'{w2.shape}, {w2.ndim}, {w2.requires_grad}, {w2.grad}, {w2.is_leaf}, {w2.grad_fn}')
print('b2 tensor', f'{b2.shape}, {b2.ndim}, {b2.requires_grad}, {b2.grad}, {b2.is_leaf}, {b2.grad_fn}')
print('z2 tensor', f'{z2.shape}, {z2.ndim}, {z2.requires_grad}, {z2.grad}, {z2.is_leaf}, {z2.grad_fn}')
print('loss', f'{loss.requires_grad}, {loss.grad}, {loss.is_leaf}, {loss.grad_fn}')

x tensor torch.Size([5]), 1, False, None, True, None
y tensor torch.Size([3]), 1, False, None, True, None
w tensor torch.Size([5, 3]), 2, True, None, True, None
b tensor torch.Size([3]), 1, True, None, True, None
z tensor torch.Size([3]), 1, True, None, False, <AddBackward0 object at 0x000001C5FF77D160>

y2 tensor torch.Size([1]), 1, False, None, True, None
w2 tensor torch.Size([3]), 1, True, None, True, None
b2 tensor torch.Size([1]), 1, True, None, True, None
z2 tensor torch.Size([1]), 1, True, None, False, <AddBackward0 object at 0x000001C5FF77D0A0>
loss True, None, False, <BinaryCrossEntropyWithLogitsBackward0 object at 0x000001C5FF77D2B0>


C:\Users\kdp\AppData\Local\Temp\ipykernel_8588\1569453660.py:5: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\b\abs_6fueooay2f\croot\pytorch-select_1707342446212\work\build\aten\src\ATen/core/TensorBody.h:494.)
  print('z tensor', f'{z.shape}, {z.ndim}, {z.requires_grad}, {z.grad}, {z.is_leaf}, {z.grad_fn}')
C:\Users\kdp\AppData\Local\Temp\ipykernel_8588\1569453660.py:11: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for 

In [44]:
print(w2, w2.grad)
print(b2, b2.grad)
print(w, w.grad)
print(b, b.grad)

tensor([-1.1450, -1.7923,  1.5257], requires_grad=True) None
tensor([-1.2552], requires_grad=True) None
tensor([[-0.0450,  0.0256, -1.5867],
        [ 0.0158,  0.1182,  1.4821],
        [-0.9300,  0.2469,  1.8194],
        [-0.9203, -0.1984, -0.3153],
        [-0.9907, -1.6816, -1.6044]], requires_grad=True) None
tensor([-0.3004,  1.3383, -2.1216], requires_grad=True) None


In [45]:
loss.backward()

In [46]:
print(w2, w2.grad)
print(b2, b2.grad)
print(w, w.grad)
print(b, b.grad)

tensor([-1.1450, -1.7923,  1.5257], requires_grad=True) tensor([-0.9141, -0.0435, -0.6707])
tensor([-1.2552], requires_grad=True) tensor([0.2883])
tensor([[-0.0450,  0.0256, -1.5867],
        [ 0.0158,  0.1182,  1.4821],
        [-0.9300,  0.2469,  1.8194],
        [-0.9203, -0.1984, -0.3153],
        [-0.9907, -1.6816, -1.6044]], requires_grad=True) tensor([[-0.3301, -0.5167,  0.4399],
        [-0.3301, -0.5167,  0.4399],
        [-0.3301, -0.5167,  0.4399],
        [-0.3301, -0.5167,  0.4399],
        [-0.3301, -0.5167,  0.4399]])
tensor([-0.3004,  1.3383, -2.1216], requires_grad=True) tensor([-0.3301, -0.5167,  0.4399])
