### 24.03.13. 임소영 미니테스트

1. tensor

2. 
- 데이터의 input과 output을 위해 사용되는 객체이다.

3. int8, int16, int32, int64     float8, float16, float32, float64
8비트는 1바이트와 같다.

In [33]:
# 4

import torch

value = torch.tensor([10, -5, 1.4, 7, 0, -1, 0], dtype=bool)
print(value.ndim)
print(value.shape)
print(value.dtype)
print(value)

1
torch.Size([7])
torch.bool
tensor([ True,  True,  True,  True, False,  True, False])


In [34]:
# 5 
value = torch.zeros((10, 10))
print(value)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [35]:
# 6
value = torch.eye(5)
print(value)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [36]:
# 7
value = torch.eye(5,3)
print(value)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [37]:
# 8
import numpy as np
value = np.array(range(1, 100, 7))
print(value)


item = torch.tensor(value, dtype = torch.float32)
print(item)

[ 1  8 15 22 29 36 43 50 57 64 71 78 85 92 99]
tensor([ 1.,  8., 15., 22., 29., 36., 43., 50., 57., 64., 71., 78., 85., 92.,
        99.])


In [38]:
# 9
file = 'flower.jpg'
picture = torch.tensor(file, dtype = torch.int8)
print(picture)

TypeError: new(): invalid data type 'str'

In [45]:
# 10
# (1)
value = torch.randint(low = 1, high = 100, size = (10,))
print(f"(1) : {value} \n{value.ndim}D")

(1) : tensor([ 2, 73, 24, 97, 38, 40, 80, 85, 19, 71]) 
1D


In [46]:
# (2)
value = torch.reshape(value, shape = (1,1,10))
print(f"(2) : {value} \n{value.ndim}D")

(2) : tensor([[[ 2, 73, 24, 97, 38, 40, 80, 85, 19, 71]]]) 
3D


In [49]:
# (3)
value = torch.squeeze(value, shape = (2,5,1))
print(f"(3) : {value} \n{value.ndim}D")

TypeError: squeeze() received an invalid combination of arguments - got (Tensor, shape=tuple), but expected one of:
 * (Tensor input)
 * (Tensor input, int dim)
      didn't match because some of the keywords were incorrect: shape
 * (Tensor input, tuple of ints dim)
      didn't match because some of the keywords were incorrect: shape
 * (Tensor input, name dim)
      didn't match because some of the keywords were incorrect: shape


In [ ]:
# (4)


In [52]:
# 11
korean = torch.tensor([90, 70, 80], dtype = torch.float)
english = torch.tensor([70, 100, 80], dtype = torch.float)
math = torch.tensor([99, 88, 77], dtype = torch.float)

print('(1)')
print(korean, english, math)

(1)
tensor([90., 70., 80.]) tensor([ 70., 100.,  80.]) tensor([99., 88., 77.])


In [53]:
print('(2)')
print(korean.sum(), korean.mean(), korean.max())
print(english.sum(), english.mean(), english.max())
print(math.sum(), math.mean(), math.max())

(2)
tensor(240.) tensor(80.) tensor(90.)
tensor(250.) tensor(83.3333) tensor(100.)
tensor(264.) tensor(88.) tensor(99.)


In [70]:
print('(3)')
list = [korean[0], english[0], math[0]]
print(sum(list), max(list))
print((sum(list))/3)

(3)
tensor(259.) tensor(99.)
tensor(86.3333)


In [66]:
# 12
korean = torch.tensor([90, 70, 80], dtype = torch.float)
english = torch.tensor([70, 100, 80], dtype = torch.float)
math = torch.tensor([99, 88, 77], dtype = torch.float)
data = torch.tensor([5, 2, 0.7], dtype = torch.float)

print(f"(1) \n {korean} \n {english} \n {math} \n {data}")

(1) 
 tensor([90., 70., 80.]) 
 tensor([ 70., 100.,  80.]) 
 tensor([99., 88., 77.]) 
 tensor([5.0000, 2.0000, 0.7000])


In [67]:
print('(2)')
print(korean.add(data), english.add(data), math.add(data))
print(korean.sub(data), english.sub(data), math.sub(data))
print(korean.mul(data), english.mul(data), math.mul(data))
print(korean.div(data), english.div(data), math.div(data))

(2)
tensor([95.0000, 72.0000, 80.7000]) tensor([ 75.0000, 102.0000,  80.7000]) tensor([104.0000,  90.0000,  77.7000])
tensor([85.0000, 68.0000, 79.3000]) tensor([65.0000, 98.0000, 79.3000]) tensor([94.0000, 86.0000, 76.3000])
tensor([450., 140.,  56.]) tensor([350., 200.,  56.]) tensor([495.0000, 176.0000,  53.9000])
tensor([ 18.0000,  35.0000, 114.2857]) tensor([ 14.0000,  50.0000, 114.2857]) tensor([ 19.8000,  44.0000, 110.0000])


In [69]:
print('(3)')
print(korean.matmul(data), english.matmul(data), math.matmul(data))

(3)
tensor(646.) tensor(606.) tensor(724.9000)
